name: Build HTML

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Check out source so we can work on it
      - name: Build
        uses: hinkleydev/SadeWiki@v0 # Build wiki
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3 # Upload built site
        with:
          path: ${{ github.workspace }}/docs
          name: wiki
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    steps:
      - name: Deploy to GitHub Pages # Upload the artifact
        uses: actions/deploy-pages@v4
        with:
          artifact_name: wiki
